import { StyleSheet } from "react-native";

export const getStyle = () => {
    return StyleSheet.create({
        safeArea: {
            flex: 1,
            width: '100%',
            backgroundColor: '#f0f4f8',
        },
        scrollContent: {
            flexGrow: 1,
            width: '100%',
            padding: 20,
            paddingBottom: 40,
        },
        titulo: {
            fontSize: 22,
            fontWeight: 'bold',
            color: '#1a3c5e',
            marginBottom: 24,
            textAlign: 'center',
        },
        label: {
            fontSize: 13,
            fontWeight: '600',
            color: '#555',
            marginBottom: 6,
            marginTop: 14,
            textTransform: 'uppercase',
            letterSpacing: 0.5,
        },
        input: {
            backgroundColor: '#fff',
            borderWidth: 1,
            borderColor: '#d0d7de',
            borderRadius: 10,
            paddingHorizontal: 14,
            paddingVertical: 12,
            fontSize: 15,
            color: '#222',
        },
        pickerWrapper: {
            backgroundColor: '#fff',
            borderWidth: 1,
            borderColor: '#d0d7de',
            borderRadius: 10,
            overflow: 'hidden',
            minHeight: 52,
            justifyContent: 'center',
        },
        pickerNative: {
            height: 52,
            width: '100%',
        },
        selectButton: {
            minHeight: 52,
            borderWidth: 1,
            borderColor: '#d0d7de',
            borderRadius: 10,
            backgroundColor: '#fff',
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            paddingHorizontal: 14,
        },
        selectButtonText: {
            fontSize: 15,
            color: '#222',
        },
        selectChevron: {
            fontSize: 12,
            color: '#1a3c5e',
        },
        linhaData: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 8,
        },
        inputMeia: {
            flex: 1,
        },
        separador: {
            fontSize: 14,
            color: '#888',
            paddingHorizontal: 4,
        },
        periodoInfo: {
            marginTop: 8,
            fontSize: 13,
            color: '#1a3c5e',
            fontWeight: '600',
        },
        periodoErro: {
            marginTop: 8,
            fontSize: 13,
            color: '#b42318',
        },
        periodoAviso: {
            paddingHorizontal: 10,
            paddingVertical: 12,
            fontSize: 13,
            color: '#667085',
        },
        tabelaContainer: {
            backgroundColor: '#fff',
            borderRadius: 10,
            borderWidth: 1,
            borderColor: '#d0d7de',
            overflow: 'hidden',
            marginTop: 6,
        },
        tabelaHeader: {
            flexDirection: 'row',
            backgroundColor: '#1a3c5e',
            paddingVertical: 10,
            paddingHorizontal: 8,
        },
        tabelaLinha: {
            flexDirection: 'row',
            paddingVertical: 14,
            paddingHorizontal: 8,
            borderBottomWidth: 1,
            borderColor: '#eef0f3',
        },
        linhaSelecionada: {
            backgroundColor: '#ddeeff',
        },
        colunaHorario: {
            width: 95,
            fontSize: 13,
            color: '#333',
        },
        colunaDia: {
            flex: 1,
            textAlign: 'center',
            fontSize: 13,
            color: '#aaa',
            alignItems: 'center',
        },
        slotDisponivel: {
            color: '#067647',
            fontWeight: '700',
            textAlign: 'center',
            fontSize: 12,
        },
        slotIndisponivel: {
            color: '#98a2b3',
            textAlign: 'center',
            fontSize: 12,
        },
        slotSelecionado: {
            color: '#1d4ed8',
            fontWeight: '800',
            textAlign: 'center',
            fontSize: 12,
        },
        navegacao: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            padding: 12,
            borderTopWidth: 1,
            borderColor: '#eef0f3',
        },
        btnNav: {
            paddingHorizontal: 16,
            paddingVertical: 8,
            borderRadius: 8,
            backgroundColor: '#e8edf2',
        },
        btnNavDisabled: {
            opacity: 0.45,
        },
        btnNavText: {
            fontSize: 14,
            color: '#1a3c5e',
            fontWeight: '600',
        },
        btnConfirmar: {
            backgroundColor: '#1a3c5e',
            borderRadius: 12,
            paddingVertical: 16,
            alignItems: 'center',
            marginTop: 24,
        },
        btnConfirmarText: {
            color: '#fff',
            fontSize: 16,
            fontWeight: 'bold',
            letterSpacing: 0.5,
        },
        modalBackdrop: {
            flex: 1,
            backgroundColor: 'rgba(0, 0, 0, 0.35)',
            justifyContent: 'center',
            padding: 20,
        },
        modalCard: {
            backgroundColor: '#fff',
            borderRadius: 12,
            overflow: 'hidden',
        },
        modalOption: {
            paddingVertical: 14,
            paddingHorizontal: 16,
            borderBottomWidth: 1,
            borderColor: '#eef0f3',
        },
        modalOptionText: {
            fontSize: 15,
            color: '#1f2933',
        },
        modalCancel: {
            paddingVertical: 14,
            alignItems: 'center',
            backgroundColor: '#f6f8fa',
        },
        modalCancelText: {
            fontSize: 15,
            fontWeight: '600',
            color: '#1a3c5e',
        },
        // legado
        mainWrapper: { flex: 1 },
        contentLayer: { flex: 1 },
        card: {},
        picker: {},
        pickerGroup: {},
        pickerSmall: {},
        inputLarge: {},
        inputData: {},
        linha: {},
        linhaCentro: {},
        tabelaScroll: {},
    })
}